### ISSUE TITLE
Fails to execute `yarn start` unless executing `yarn install` periodically

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aquaproj.github.io#668]
`yarn start` fails and outputs the following error.

```console
$ yarn start
Internal Error: aqua-docusaurus@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at $x.getCandidates (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:205:8149)
    at Bd.getCandidates (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:141:1311)
    at /Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:210:8334
    at Yy (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:140:53922)
    at xe (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:210:8314)
    at async Promise.allSettled (index 0)
    at async Uc (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:140:53250)
    at async /Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:210:9065
    at async Qi.startProgressPromise (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:140:137290)
    at async St.resolveEverything (/Users/shunsukesuzuki/.volta/tools/image/yarn/4.0.1/bin/yarn.js:210:7063)
```

We need to execute `yarn install` periodically.

https://github.com/aquaproj/aquaproj.github.io/pulls?q=is%3Apr+author%3Asuzuki-shunsuke+is%3Aclosed+yarn.lock

## Assumption

We update dependencies by Renovate and Dependabot.

- https://github.com/aquaproj/aquaproj.github.io/pulls?q=is%3Apr+author%3Aapp%2Frenovate+is%3Aclosed
- https://github.com/aquaproj/aquaproj.github.io/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot

## What we tried

- Enable Renovate's lockFileMaintenance https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
- Update yarn.lock by `yarn install` in CI https://github.com/aquaproj/aquaproj.github.io/pull/632
  - https://github.com/aquaproj/aquaproj.github.io/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate+%22chore%28deps%29%3A+lock+file+maintenance%22+in%3Atitle

**Comment by suzuki-shunsuke** [comment]
I tried to replace yarn with npm.

- https://github.com/aquaproj/aquaproj.github.io/pull/852

**Comment by suzuki-shunsuke** [comment]
Recently, this issue doesn't occur. So I close this issue.
